### ISSUE TITLE
Loading a cooler from bedpe data

### ISSUE THREAD

**Issue by pkerpedjiev** [mirnylab/cooler#90] opened 2017-10-18 16:08 UTC
From:  https://github.com/hms-dbmi/higlass/issues/100#issuecomment-337638880

> "To convert data to cooler, there's the cooler package, which provides a convenient command-line interface for loading data from text files (e.g. bedpe) to cooler files."
Which information are expected to be in the bedpe file ? is it all pairs of interaction ? or could it be already binned ?
And I was wondering how you deal with the normalization ? I saw a "--no-balance" option, but can I use already binned and normalized data to generate the .cool file ?
Thanks !

**Comment by pkerpedjiev** [comment] 2017-10-18 17:41
> Thank you very much for your fast answer !
Adding a piece of context here ; I'm developing HiC-Pro which is a pipeline for Hi-C data processing, and several users ask me to provide a converter hicpro2higlass able to convert the HiC-pro outputs into the higlass input.
HiC-pro provides the list of valid pairs, and the binned matrix.
My feeling (but tell me if I'm wrong) is that if I use the list of valid pairs, the cooler tool will generate the binned data at different resolutions, which sounds better to zoom at different resolution ! otherwise, if I provide already binned data, I will just be able to look a the data at this resolution ?
One more thing, I'm following the tutorial here to create .cool files ;
https://github.com/hms-dbmi/higlass/wiki#cooler-files
But at this point ;
cooler cload bins.10kb.bed $CONTACTS_FILE.sorted out.cool
it seems that something is missing ?
Error: No such command "bins.20kb.bed".
Any idea ?
Thanks

**Comment by pkerpedjiev** [comment] 2017-10-18 17:50
@nservant Continuing our thread from the HiGlass repository here since these questions are unique to cooler.

> My feeling (but tell me if I'm wrong) is that if I use the list of valid pairs, the cooler tool will generate the binned data at different resolutions, which sounds better to zoom at different resolution ! otherwise, if I provide already binned data, I will just be able to look a the data at this resolution ?

Cooler can take binned data as input and generate a single resolution cooler file using the `cload` command. This can be converted to multi-res format using the `cooler zoomify` command. If you use the `--no-balance` option, it will recursively reaggregate the data at lower resolutions.

If you have normalized data, then this doesn't make sense. You'll need to provide normalized data at each resolution you want to look at.

If you just provide one resolution, you'll be able to look at just that resolution but you won't be able to zoom out. 

> cooler cload bins.10kb.bed $CONTACTS_FILE.sorted out.cool
it seems that something is missing ?
Error: No such command "bins.20kb.bed".

Did you generate the 20Kb bins?

    BINSIZE=20000;
    cooler makebins $CHROMSIZES_FILE $BINSIZE > bins.10kb.bed

**Comment by nvictus** [comment] 2017-10-18 18:02
Cooler can ingest both Hi-C pro style sparse matrices (with a separate bin definition file) or BEDPE files indexed with pairix. These correspond to binned data. Valid pairs/contacts/interactions are loaded with `cooler cload`.

Cooler's schema is sort of a binary equivalent of the bins + upper triangle sparse triple files that Hi-C pro produces. Happy to help improve support (and documentation) for this!

**Comment by nvictus** [comment] 2017-10-18 18:14
```
cooler cload bins.10kb.bed $CONTACTS_FILE.sorted out.cool
it seems that something is missing ?
Error: No such command "bins.20kb.bed".
```
There's a subcommand missing. We currently support text pairs files indexed with Tabix or Pairix, as well as HDF5 files from our old hiclib pipeline. 

1. Produces a sorted, indexed pairs file (using pairix by default). Make sure your chromosomes file has them ordered the way you want them to be displayed. You may need to specify the column numbers corresponding to chrom1, pos1, chrom2, pos2. (`cooler csort --help`).
`cooler csort $CONTACTS_FILE $CHROMSIZES_FILE`

If your pairs file is already sorted and upper triangular, you can just use `bgzip` and `pairix`.

2. Bin the pairs into a contact matrix:
`cooler cload` **`pairix`** `bins.20kb.bed $CONTACTS_FILE.sorted.gz out.cool`

You can skip creating the `bins.20kb.bed` with the shortcut `$CHROMSIZES_FILE:20000`.

**Comment by pkerpedjiev** [comment] 2017-10-18 18:17
Whoops! I changed the documentation in the HiGlass wiki to add the missing subcommand.

**Comment by nservant** [comment] 2017-10-18 18:17
looks great !
Let me know what you think if I provide ;
* On one hand, I can try to generate cooler file from one HiC-Pro matrix file (raw or normalized) at single resolution. In this case, @nvictus, would you have an example of how to generate .cool file from HiC-pro matrix format ?
* And on the other hand, I think it make sense to start from the list of valid pairs and let cooler bin the data (and normalized them if I remove the --no-balance option ?). In this case, I can easily generate bedp file.

Regarding the error I send before, I just think that the command in the wiki ;
`cooler cload bins.10kb.bed $CONTACTS_FILE.sorted out.cool`
should be
`cooler cload pairix bins.10kb.bed $CONTACTS_FILE.sorted out.cool`

Thanks again for your help. And congrats for developing such a great tool !

**Comment by nservant** [comment] 2017-10-18 18:18
lol ok thanks for the update !

**Comment by nvictus** [comment] 2017-10-18 18:55
> would you have an example of how to generate .cool file from HiC-pro matrix format ?

Loading a HiC-Pro matrix file should just be:
```
cooler load -f coo $HICPROBINS_FILE $HICPROCOO_FILE out.cool
```
So you won't need to convert to BEDPE... unless I am making some false assumptions about the format. Do you have a small example HiCPro output you could send me?

> I think it make sense to start from the list of valid pairs and let cooler bin the data.

No-balance is actually became a no-op. Pass `--balance` to make it normalize.

**Comment by nservant** [comment] 2017-10-18 19:27
Sure. There is a toy example here :
https://zerkalo.curie.fr/partage/HiC-Pro/HiCPro_results/HiC_Pro_v2.7.9_test_data/hic_results/
There are the matrix files at different bin levels or the allValidPairs file in data/ with the list of valid pairs. 
I'll play with it tomorrow. We keep in touch
Thank again for your help !

**Comment by nservant** [comment] 2017-10-19 12:49
Hi guys,
I did some tests, and have two issues ;
- From a Matrix, the command from @nvictus  works well.
`cooler load -f coo $HICPROBINS_FILE $HICPROCOO_FILE out.cool`
Then, I tried to load them in HiGlass using ;
`sudo docker exec higlass-container python higlass-server/manage.py  ingest_tileset --filename /home/nservant/Desktop/hicpro_dev/out.multi.cool --datatype matrix --filetype cooler `
But the input file is not found ...
`FileNotFoundError: [Errno 2] No such file or directory: '/home/nservant/Desktop/hicpro_dev/out.multi.cool'`

- Then I also tried from the list of valid pairs, but there is something wrong with the chromosome name.
$ head chrom_mm9.sizes 
chr1	197195432
chr2	181748087
chr3	159599783
chr4	155630120
chr5	152537259
chr6	149517037
chr7	152524553
chr8	131738871
chr9	124076172
chr10	129993255
$ head contacts.bedpe
chr11	13790998	-	chr11	110518448	+	1
chr11	51975824	-	chr11	110593379	+	1
chr11	109010040	+	chr11	113999488	-	1
chr11	109010049	+	chr11	109212484	-	1
chr11	109010053	+	chr11	114733361	-	1
chr11	109010054	+	chr11	109035950	+	1
chr11	109010068	+	chr11	109374183	+	1
chr11	109010072	+	chr11	109013743	-	1
chr11	109010073	+	chr11	109050628	+	1
chr11	109010074	+	chr11	109388547	-	1

Note that here this is small file with reads from the chr11 only.
`cooler cload pairix bins.20kb.bed $CONTACTS_FILE.sorted out.cool`
/usr/local/lib/python2.7/dist-packages/cooler/_binning.py:382: UserWarning: Did not find contig  'chr1' in contact list file.
  " '{}' in contact list file.".format(chrom))
/usr/local/lib/python2.7/dist-packages/cooler/_binning.py:382: UserWarning: Did not find contig  'chr2' in contact list file.
  " '{}' in contact list file.".format(chrom))
(...)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/groupby.py", line 1826, in levels
    return [ping.group_index for ping in self.groupings]
AttributeError: 'Int64Index' object has no attribute 'group_index'

I will continue to try to fix it in case I miss something.
thanks

**Comment by pkerpedjiev** [comment] 2017-10-19 14:41
So for loading into HiGlass part, the issue is simple. The Docker container that you're running (`higlass-container`) is like a little virtual machine. It only has access to its own filesystem. The file that you passed in, `/home/nservant/Desktop/hicpro_dev/out.multi.cool` is on your filesystem and not on the Docker's. To access files on your local filesystem from Docker you need to mount a local directory into the container. If you ran the docker command from the wiki (https://github.com/hms-dbmi/higlass/wiki) you've actually already done this:

```
docker run --detach \
           --publish 8989:80 \
           --volume ~/hg-data:/data \
           --volume ~/tmp:/tmp \
           --name higlass-container \
           gehlenborglab/higlass:v0.2.15
```

With this command, you've mounted your local `~/hg-data` to Docker's `/data` and your local `~/tmp` to Docker's `/tmp`. So to load your file, you need to place it into your local `~/tmp` directory: 

    cp /home/nservant/Desktop/hicpro_dev/out.multi.cool ~/tmp/

Then reference it as `/tmp/out.multi.cool` in the Docker container. Your ingest command should look like this:

```
sudo docker exec higlass-container python higlass-server/manage.py ingest_tileset \
    --filename /tmp/out.multi.cool \
    --datatype matrix \
    --filetype cooler
```

**Comment by nservant** [comment] 2017-10-19 15:01
Thanks. It make sense.
One more comment, would you plan to generate a singularity container of higlass ?
Docker is great but you need to be root to manage the container. For instance I was very interested in creating a higlass instance open to all teams of my institute but I'm not root on the system ... and singularity offers the possibility to handle container without root rights.
Thanks again for all your help



Envoyé depuis mon smartphone Samsung Galaxy.


-------- Message d'origine --------
De : Peter Kerpedjiev <notifications@github.com>
Date : 19/10/2017 16:41 (GMT+01:00)
À : mirnylab/cooler <cooler@noreply.github.com>
Cc : Servant Nicolas <Nicolas.Servant@curie.fr>, Mention <mention@noreply.github.com>
Objet : Re: [mirnylab/cooler] Loading a cooler from bedpe data (#90)


So for loading into HiGlass part, the issue is simple. The Docker container that you're running (higlass-container) is like a little virtual machine. It only has access to its own filesystem. The file that you passed in, /home/nservant/Desktop/hicpro_dev/out.multi.cool is on your filesystem and not on the Docker's. To access files on your local filesystem from Docker you need to mount a local directory into the container. If you ran the docker command from the wiki (https://github.com/hms-dbmi/higlass/wiki) you've actually already done this:

docker run --detach \
           --publish 8989:80 \
           --volume ~/hg-data:/data \
           --volume ~/tmp:/tmp \
           --name higlass-container \
           gehlenborglab/higlass:v0.2.15


With this command, you've mounted your local ~/hg-data to Docker's /data and your local ~/tmp to Docker's /tmp. So to load your file, you need to place it into your local ~/tmp directory:

cp /home/nservant/Desktop/hicpro_dev/out.multi.cool ~/tmp/


Then reference it as /tmp/out.multi.cool in the Docker container. Your ingest command should look like this:

sudo docker exec higlass-container python higlass-server/manage.py ingest_tileset \
    --filename /tmp/out.multi.cool \
    --datatype matrix \
    --filetype cooler

**Comment by pkerpedjiev** [comment] 2017-10-19 15:09
I actually hand't heard of singularity until you just mentioned it. Thanks for bringing it up! Unfortunately this will be slightly lower priority at the moment but I've added an issue to the higlass repository to make sure we don't forget about it (https://github.com/hms-dbmi/higlass/issues/161).

**Comment by nvictus** [comment] 2017-10-20 16:14
Singularity is new to me too! Note that you don't need to be root to use docker. As long as your sysadmin can add you to the docker user group, you'll be able to run it without sudo privileges.

https://docs.docker.com/engine/installation/linux/linux-postinstall/

**Comment by nvictus** [comment] 2017-10-20 16:52
I see one discrepancy. It looks like HiCPro's bin IDs are 1-based. `cooler load -f coo` assumes the bin IDs in the matrix file are zero-based. I could add an option for 1-based matrix files.

**Comment by nvictus** [comment] 2017-10-31 22:53
I added a `--one-based` flag to `cooler load -f coo` to handle HiCPro files correctly in v0.7.6. Right now, it ignores the fourth column of the HiCPro bed file, and assigns zero-based absolute IDs to the bins on each line of file. The IDs in the HiCPro matrix file are then interpreted as 1-based and are decremented by 1 accordingly. (Everything in cooler is zero-based!)

If these assumptions are incorrect, let me know.

**Comment by nservant** [comment] 2017-11-09 14:04
Hi. thanks for the update.

I installed the new version, and generate new cool file with --one-based 
option.

However, when I try to load it into higlass, nothing happens.

Is there a way to access a log file somewhere, to have an idea of what's 
going wrong ?

I used a very small data (5Mb on chr11). Could it be an issue ?

Best

nicolas


Le 31/10/2017 à 23:53, Nezar Abdennur a écrit :

**Comment by nservant** [comment] 2017-11-09 14:56
Actually, I think that the .cool file I generated is good, but cannot be 
loaded into Higlass.

I put the file here : https://zerkalo.curie.fr/partage/temp/mat.cool

Could you please have a look at it ?

Thanks


Le 31/10/2017 à 23:53, Nezar Abdennur a écrit :

**Comment by nservant** [comment] 2017-11-13 20:34
Hi guys,

Finally, It works. I think I have now a first version able to convert a 
HiC-pro matrix into a .cool file.
In addition, I think it might be of interest to do the same starting 
from a list of valid interaction (bedp) instead of a matrix.
Herei s what I'm using ;

cooler csort --nproc 4 -c1 1 -p1 2 -s1 3 -c2 4 -p2 5 -s2 6 \
        -o contacts.bedpe.sorted  \
        contacts.bedpe \
        $CHROMSIZES_FILE

cooler makebins $CHROMSIZES_FILE 20000 > bins.bed
cooler cload pairix bins.bed contacts.bedpe.sorted $out
cooler zoomify $out

It runs, but the .mcool file looks empty in Higlass.
The python module also returns an error

 >>> c = cooler.Cooler('out.mcool')
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File 
"/usr/local/lib/python2.7/dist-packages/cooler-0.7.6-py2.7.egg/cooler/api.py", 
line 78, in __init__
     _ct = chroms(grp)
   File 
"/usr/local/lib/python2.7/dist-packages/cooler-0.7.6-py2.7.egg/cooler/api.py", 
line 366, in chroms
     .append(pandas.Index(h5['chroms'].keys()))
   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
   File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 
167, in __getitem__
     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
   File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'chroms' doesn't exist)"

Any idea on what's going wrong ?

Last question, It works if the bedp file looks like ;

hg19_chr11    13790998    -    hg19_chr11    110518448    +    1
hg19_chr11    51975824    -    hg19_chr11    110593379    +    1
hg19_chr11    109010040    +    hg19_chr11    113999488    -    1

Can I remove the "hg19_" ?? or do you expect something special here ??

Thanks

Nicolas


Le 20/10/2017 à 18:52, Nezar Abdennur a écrit :

**Comment by nservant** [comment] 2017-11-13 21:32
Sorry, one more question. I try to use the cooler csort tool, but get an 
error ;

   File "/usr/local/lib/python2.7/dist-packages/pandas/core/groupby.py", 
line 1826, in levels
     return [ping.group_index for ping in self.groupings]
AttributeError: 'Index' object has no attribute 'group_index'

Thanks for your help


Le 20/10/2017 à 18:52, Nezar Abdennur a écrit :

**Comment by nvictus** [comment] 2017-11-15 03:39
The `Cooler` class doesn't support mcools, but you can access any Cooler within a .mcool file with the '::' separator: e.g. `cooler.Cooler('out.cool::10')`.

**Comment by nvictus** [comment] 2019-01-05 00:56
I think the issues here have been sorted out, but I've lost track of this thread. Some updates that should be helpful:

* `cooler load` can ingest one-based inputs, and `cooler dump` can dump one-based output like HiCPro
* No input sorting is required anymore for `cooler cload pairs` and `cooler load`
* Loading floating point values is supported, and `cooler coarsen` and `zoomify` now propagate those values properly.
* The [new mcool](https://cooler.readthedocs.io/en/latest/schema.html#file-flavors) layout (supported by HiGlass) is now the default output of cooler commands.

@nservant, let me know if you still run into issues, or if we can close this issue.

**Comment by nvictus** [comment] 2020-06-24 01:34
Please re-open if this issue is still relevant.

**Closed by nvictus** 2020-06-24 01:34 UTC
