### ISSUE TITLE
Extending metadata

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooler#100] opened 2018-01-08 15:39 UTC
Hi,

I was just thinking it would be awesome to be able to extend the metadata in the cooler with things like Pc(s) or expected values so that we don't have to store separate files for these things. Maybe it is possible now already?

Thanks!

**Comment by nvictus** [comment] 2020-06-24 01:35
Duplicate of #112, though much discussion has happened since then.

**Closed by nvictus** 2020-06-24 01:35 UTC
