### ISSUE TITLE
Error - data type 'int64 for float64' 

### ISSUE THREAD

**Issue by nservant** [mirnylab/cooler#117] opened 2018-04-23 11:32 UTC
Hi,
After multiple testing (v0.7.6), it seems that the cooler load and zoomify do not expect to deal with float values.
`ValueError: cannot safely convert passed user dtype of int64 for float64 dtyped data in column 2`

It means that only raw Hi-C counts can be loaded, but not normalized or transformed counts (pearson  correlation maps, observed/expected, etc.)
It would be great if future versions of cooler could fixed that to allow users to play with any type of data transformation and see them into HiGlass.
Best
N

**Comment by nvictus** [comment] 2019-01-05 00:32
Float propagation issues should all be fixed now (v0.8)!

**Comment by nvictus** [comment] 2019-01-20 20:40
Closing this. Please re-open if any issues do persist.

**Closed by nvictus** 2019-01-20 20:40 UTC

**Comment by danydoerr** [comment] 2019-02-12 18:37
This issue seems have been re-emerged. cooler load --count-as-float is broken in release v0.8.3. I haven't tested with the trunk.

**Comment by nvictus** [comment] 2019-02-13 07:27
Thanks for reporting. Does `--field count=7:dtype=float` work as an alternative?

**Comment by danydoerr** [comment] 2019-02-13 13:50
Thanks Nezar! 
Your suggestion seems to work at first (it sets the field type properly), but then cooler breaks at another place:

```
INFO:cooler.cli.load:fields: {'count': 6, 'bin2_id': 1, 'bin1_id': 0}
INFO:cooler.cli.load:dtypes: {'count': dtype('float64'), 'bin2_id': <type 'int'>, 'bin1_id': <type 'int'>}
INFO:cooler.cli.load:symmetric-upper: True
INFO:cooler.create:Writing chunk 0: /tmp/tmphkJLtB.multi.cool::0
INFO:cooler.create:Creating cooler at "/tmp/tmphkJLtB.multi.cool::/0"
INFO:cooler.create:Writing chroms
INFO:cooler.create:Writing bins
INFO:cooler.create:Writing pixels
Traceback (most recent call last):
  File "/prj/tools/python2/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/prj/tools/python2/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/prj/tools/python2/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/prj/tools/python2/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/prj/tools/python2/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/prj/tools/python2/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/prj/tools/python2/lib/python2.7/site-packages/cooler/cli/load.py", line 305, in load
    h5opts=h5opts
  File "/prj/tools/python2/lib/python2.7/site-packages/cooler/create/_create.py", line 641, in create_from_unordered
    columns=columns, dtypes=dtypes, mode='a', **kwargs)
  File "/prj/tools/python2/lib/python2.7/site-packages/cooler/create/_create.py", line 574, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/prj/tools/python2/lib/python2.7/site-packages/cooler/create/_create.py", line 230, in write_pixels
    dset[nnz:nnz+n] = chunk[col]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/prj/tools/python2/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 708, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)                                                                                                                                                       File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
IOError: Can't write data (no appropriate function for conversion path)
```
I only could get cooler to work fixing the data type setting of the count column in dictionary output_field_dtypes in cli.load.

**Comment by nvictus** [comment] 2019-02-15 17:41
Would you mind sending a sample file? I can't seem to reproduce it.

**Comment by nvictus** [comment] 2019-02-15 20:31
Thanks @danydoerr. My mistake, I thought you were inputting a BG2-type file, where `count` is in column 7, but you were using a COO file. If you do `--field count=3:dtype=float`, it will work. In fact, because `count` is standard you can omit the column number so `--field count:dtype=float` will work too.

**Comment by danydoerr** [comment] 2019-02-15 21:05
Thanks, works!
