### ISSUE TITLE
rename_chroms

### ISSUE THREAD

**Issue by Derfen3001** [mirnylab/cooler#147] opened 2019-01-31 15:06 UTC
Hi,

I am trying to rename the chromosomes names of some cool files but I keep getting this error.  

NameErrorTraceback (most recent call last)
<ipython-input-49-50bba4059772> in <module>()
----> 1 cooler.rename_chroms(c,dic)

/anaconda3/lib/python2.7/site-packages/cooler/create/_create.pyc in rename_chroms(clr, rename_dict, h5opts)
    372 
    373     with clr.open('r+') as f:
--> 374         _rename_chroms(f, rename_dict, h5opts)
    375 
    376 

/anaconda3/lib/python2.7/site-packages/cooler/create/_create.pyc in _rename_chroms(grp, rename_dict, h5opts)
    318 
    319 def _rename_chroms(grp, rename_dict, h5opts):
--> 320     chroms = cooler.core.get(grp['chroms']).set_index('name')
    321     n_chroms = len(chroms)
    322     new_names = np.array(chroms.rename(rename_dict).index.values,

NameError: global name 'cooler' is not defined

I am running the command in this way:  cooler.rename_chroms(c,dic)
Where c is the cool file and dic is a dictionary with the names I want,  created in this way: 

dic={chr:'chr'+str(chr) for chr in c.chromnames}

Any suggestion?

Cheers,

Stefano

**Comment by golobor** [comment] 2019-01-31 19:54
just talked to @nvictus who pointed out that it's a bug in imports. Will be
fixed soon!

https://github.com/mirnylab/cooler/blob/0a59f858530d6768ff0dc5f96403611898fa38ec/cooler/create/_create.py#L320

**Comment by nvictus** [comment] 2019-02-11 22:51
Fixed in v0.8.3

**Comment by Derfen3001** [comment] 2019-02-12 13:30
Hi, 
   I downloaded the new version, but the command is not changing the chromosomes names and it does not return whatsoever error. 

I am using the same code of above

Cheers,

Stefano

**Comment by nvictus** [comment] 2019-02-12 13:36
Hmm. You may need to recreate the cooler object because the old names are cached. Could you try that?

**Comment by Derfen3001** [comment] 2019-02-12 13:42
I tried using a new cooler, nothing.

**Comment by nvictus** [comment] 2019-02-12 13:47
Could you send me an example file to reproduce?

**Comment by Derfen3001** [comment] 2019-02-12 13:49
Sorry, my bad, if I reload the file the chromosome names are changed. 

cheers,

Stefano

**Comment by nvictus** [comment] 2019-02-12 13:54
Great! We should make `rename_chroms()` refresh the `Cooler` object so that that won't be required. I'll re-open for that.

**Closed** 2019-04-04 22:22 UTC
